/* MLton 20180613.152146-g678049ecc-dirty */
/*   created this file on Tue Aug 28 13:19:57 2018. */
/* Do not edit this file. */
/* Flag settings:  */
/*    align: 4 */
/*    atMLtons: (@MLton, --) */
/*    chunk: coalesce 4096 */
/*    closureConvertGlobalize: true */
/*    closureConvertShrink: true */
/*    codegen: rtems */
/*    contifyIntoMain: false */
/*    debug: false */
/*    defaultChar: char8 */
/*    defaultWideChar: widechar32 */
/*    defaultInt: int32 */
/*    defaultReal: real64 */
/*    defaultWord: word32 */
/*    diag passes: [] */
/*    execute passes: [] */
/*    elaborate allowConstant (default): false */
/*    elaborate allowConstant (enabled): true */
/*    elaborate allowFFI (default): false */
/*    elaborate allowFFI (enabled): true */
/*    elaborate allowPrim (default): false */
/*    elaborate allowPrim (enabled): true */
/*    elaborate allowOverload (default): false */
/*    elaborate allowOverload (enabled): true */
/*    elaborate allowRedefineSpecialIds (default): false */
/*    elaborate allowRedefineSpecialIds (enabled): true */
/*    elaborate allowSpecifySpecialIds (default): false */
/*    elaborate allowSpecifySpecialIds (enabled): true */
/*    elaborate deadCode (default): false */
/*    elaborate deadCode (enabled): true */
/*    elaborate forceUsed (default): false */
/*    elaborate forceUsed (enabled): true */
/*    elaborate ffiStr (default):  */
/*    elaborate ffiStr (enabled): true */
/*    elaborate nonexhaustiveBind (default): warn */
/*    elaborate nonexhaustiveBind (enabled): true */
/*    elaborate nonexhaustiveExnBind (default): default */
/*    elaborate nonexhaustiveExnBind (enabled): true */
/*    elaborate redundantBind (default): warn */
/*    elaborate redundantBind (enabled): true */
/*    elaborate nonexhaustiveMatch (default): warn */
/*    elaborate nonexhaustiveMatch (enabled): true */
/*    elaborate nonexhaustiveExnMatch (default): default */
/*    elaborate nonexhaustiveExnMatch (enabled): true */
/*    elaborate redundantMatch (default): warn */
/*    elaborate redundantMatch (enabled): true */
/*    elaborate nonexhaustiveRaise (default): ignore */
/*    elaborate nonexhaustiveRaise (enabled): true */
/*    elaborate nonexhaustiveExnRaise (default): ignore */
/*    elaborate nonexhaustiveExnRaise (enabled): true */
/*    elaborate redundantRaise (default): warn */
/*    elaborate redundantRaise (enabled): true */
/*    elaborate resolveScope (default): strdec */
/*    elaborate resolveScope (enabled): true */
/*    elaborate sequenceNonUnit (default): ignore */
/*    elaborate sequenceNonUnit (enabled): true */
/*    elaborate valrecConstr (default): warn */
/*    elaborate valrecConstr (enabled): true */
/*    elaborate warnUnused (default): false */
/*    elaborate warnUnused (enabled): true */
/*    elaborate allowDoDecls (default): false */
/*    elaborate allowDoDecls (enabled): true */
/*    elaborate allowExtendedNumConsts (default): false */
/*    elaborate allowExtendedNumConsts (enabled): true */
/*    elaborate allowExtendedTextConsts (default): false */
/*    elaborate allowExtendedTextConsts (enabled): true */
/*    elaborate allowLineComments (default): false */
/*    elaborate allowLineComments (enabled): true */
/*    elaborate allowOptBar (default): false */
/*    elaborate allowOptBar (enabled): true */
/*    elaborate allowOptSemicolon (default): false */
/*    elaborate allowOptSemicolon (enabled): true */
/*    elaborate allowOrPats (default): false */
/*    elaborate allowOrPats (enabled): true */
/*    elaborate allowRecordPunExps (default): false */
/*    elaborate allowRecordPunExps (enabled): true */
/*    elaborate allowSigWithtype (default): false */
/*    elaborate allowSigWithtype (enabled): true */
/*    elaborate allowVectorExps (default): false */
/*    elaborate allowVectorExps (enabled): true */
/*    elaborate allowVectorPats (default): false */
/*    elaborate allowVectorPats (enabled): true */
/*    elaborate only: false */
/*    emit main: true */
/*    export header: None */
/*    exn history: false */
/*    generated output format: executable */
/*    gc check: Limit */
/*    indentation: 3 */
/*    inlineIntoMain: true */
/*    inlineLeafA: {loops = true, repeat = true, size = Some 20} */
/*    inlineLeafB: {loops = true, repeat = true, size = Some 40} */
/*    inlineNonRec: {small = 60, product = 320} */
/*    input file: hello */
/*    keep AST: false */
/*    keep CoreML: false */
/*    keep def use: true */
/*    keep dot: false */
/*    keep Machine: false */
/*    keep passes: [] */
/*    keep RSSA: false */
/*    keep SSA: false */
/*    keep SSA2: false */
/*    keep SXML: false */
/*    keep XML: false */
/*    extra_: false */
/*    lib dir: /home/mood/rtems-dev/mlton-rtems/build/lib/mlton */
/*    lib target dir: /home/mood/rtems-dev/mlton-rtems/build/lib/mlton/targets/i386-rtems4.11 */
/*    loop ssa passes: 1 */
/*    loop ssa2 passes: 1 */
/*    loop unrolling limit: 150 */
/*    loop unswitching limit: 300 */
/*    mark cards: true */
/*    max function size: 10000 */
/*    mlb path vars: [{var = SML_LIB, path = $(LIB_MLTON_DIR)/sml}] */
/*    native commented: 0 */
/*    native live stack: false */
/*    native optimize: 1 */
/*    native move hoist: true */
/*    native copy prop: true */
/*    native copy prop cutoff: 1000 */
/*    native cutoff: 100 */
/*    native live transfer: 8 */
/*    native shuffle: true */
/*    native ieee fp: false */
/*    native split: Some 20000 */
/*    optFuel: None */
/*    optimizationPasses: [<ssa2::default>, <ssa::default>, <sxml::default>, <xml::default>] */
/*    polyvariance: Some {hofo = true, rounds = 2, small = 30, product = 300} */
/*    prefer abs paths: false */
/*    prof passes: [] */
/*    profile: None */
/*    profile branch: false */
/*    profile C: [] */
/*    profile IL: ProfileSource */
/*    profile include/exclude: [(Seq [Star [.], Or [Seq [Seq [[$], [(], [S], [M], [L], [_], [L], [I], [B], [)]]]], Star [.]], false)] */
/*    profile raise: false */
/*    profile stack: false */
/*    profile val: false */
/*    show basis: None */
/*    show basis compact: false */
/*    show basis def: true */
/*    show basis flat: true */
/*    show def-use: None */
/*    show types: true */
/*    target: i386-rtems4.11 */
/*    target arch: X86 */
/*    target OS: Rtems */
/*    type check: false */
/*    verbosity: Silent */
/*    warn unrecognized annotation: true */
/*    warn deprecated features: true */
/*    zone cut depth: 100 */
#include <c-main.h>

PRIVATE struct GC_state gcState;
PRIVATE CPointer globalCPointer [0];
PRIVATE CPointer CReturnQ;
PRIVATE Int8 globalInt8 [0];
PRIVATE Int8 CReturnI8;
PRIVATE Int16 globalInt16 [0];
PRIVATE Int16 CReturnI16;
PRIVATE Int32 globalInt32 [0];
PRIVATE Int32 CReturnI32;
PRIVATE Int64 globalInt64 [0];
PRIVATE Int64 CReturnI64;
PRIVATE Objptr globalObjptr [128];
PRIVATE Objptr CReturnP;
PRIVATE Real32 globalReal32 [0];
PRIVATE Real32 CReturnR32;
PRIVATE Real64 globalReal64 [0];
PRIVATE Real64 CReturnR64;
PRIVATE Word8 globalWord8 [0];
PRIVATE Word8 CReturnW8;
PRIVATE Word16 globalWord16 [0];
PRIVATE Word16 CReturnW16;
PRIVATE Word32 globalWord32 [0];
PRIVATE Word32 CReturnW32;
PRIVATE Word64 globalWord64 [0];
PRIVATE Word64 CReturnW64;
PRIVATE Pointer globalObjptrNonRoot [1];
PRIVATE Pointer MLton_FFI_opArgsResPtr;
static int saveGlobals (FILE *f) {
	SaveArray (globalCPointer, f);
	SaveArray (globalInt8, f);
	SaveArray (globalInt16, f);
	SaveArray (globalInt32, f);
	SaveArray (globalInt64, f);
	SaveArray (globalObjptr, f);
	SaveArray (globalReal32, f);
	SaveArray (globalReal64, f);
	SaveArray (globalWord8, f);
	SaveArray (globalWord16, f);
	SaveArray (globalWord32, f);
	SaveArray (globalWord64, f);
	return 0;
}
static int loadGlobals (FILE *f) {
	LoadArray (globalCPointer, f);
	LoadArray (globalInt8, f);
	LoadArray (globalInt16, f);
	LoadArray (globalInt32, f);
	LoadArray (globalInt64, f);
	LoadArray (globalObjptr, f);
	LoadArray (globalReal32, f);
	LoadArray (globalReal64, f);
	LoadArray (globalWord8, f);
	LoadArray (globalWord16, f);
	LoadArray (globalWord32, f);
	LoadArray (globalWord64, f);
	return 0;
}
BeginVectorInits
VectorInitElem (1, 16, 11, (pointer)"afnosupport")
VectorInitElem (1, 65, 5, (pointer)"nostr")
VectorInitElem (1, 15, 12, (pointer)"addrnotavail")
VectorInitElem (1, 36, 5, (pointer)"ilseq")
VectorInitElem (1, 59, 6, (pointer)"nolink")
VectorInitElem (1, 123, 2, (pointer)" [")
VectorInitElem (1, 20, 6, (pointer)"badmsg")
VectorInitElem (1, 113, 35, (pointer)"Top-level suffix raised exception.\n")
VectorInitElem (1, 78, 5, (pointer)"proto")
VectorInitElem (1, 114, 8, (pointer)"flushOut")
VectorInitElem (1, 93, 16, (pointer)"Thread.atomicEnd")
VectorInitElem (1, 120, 4, (pointer)"Io: ")
VectorInitElem (1, 47, 8, (pointer)"multihop")
VectorInitElem (1, 127, 16, (pointer)"MLton.Exit.exit(")
VectorInitElem (1, 103, 4, (pointer)"Fail")
VectorInitElem (1, 45, 5, (pointer)"mlink")
VectorInitElem (1, 13, 5, (pointer)"acces")
VectorInitElem (1, 62, 10, (pointer)"noprotoopt")
VectorInitElem (1, 34, 11, (pointer)"hostunreach")
VectorInitElem (1, 33, 4, (pointer)"fbig")
VectorInitElem (1, 67, 7, (pointer)"notconn")
VectorInitElem (1, 25, 11, (pointer)"connrefused")
VectorInitElem (1, 95, 32, (pointer)"exit must have 0 <= status < 256")
VectorInitElem (1, 110, 8, (pointer)"<stdout>")
VectorInitElem (1, 46, 7, (pointer)"msgsize")
VectorInitElem (1, 115, 13, (pointer)"hello world!\n")
VectorInitElem (1, 98, 1, (pointer)"\n")
VectorInitElem (1, 35, 4, (pointer)"idrm")
VectorInitElem (1, 17, 5, (pointer)"again")
VectorInitElem (1, 124, 8, (pointer)"SysErr: ")
VectorInitElem (1, 64, 4, (pointer)"nosr")
VectorInitElem (1, 121, 6, (pointer)"Fail: ")
VectorInitElem (1, 118, 14, (pointer)"\" failed with ")
VectorInitElem (1, 77, 4, (pointer)"pipe")
VectorInitElem (1, 117, 5, (pointer)"Fail8")
VectorInitElem (1, 99, 28, (pointer)"control shouldn\'t reach here")
VectorInitElem (1, 104, 6, (pointer)"SysErr")
VectorInitElem (1, 107, 4, (pointer)"Size")
VectorInitElem (1, 27, 6, (pointer)"deadlk")
VectorInitElem (1, 38, 4, (pointer)"intr")
VectorInitElem (1, 72, 5, (pointer)"notty")
VectorInitElem (1, 41, 6, (pointer)"isconn")
VectorInitElem (1, 23, 5, (pointer)"child")
VectorInitElem (1, 81, 5, (pointer)"range")
VectorInitElem (1, 69, 8, (pointer)"notempty")
VectorInitElem (1, 63, 5, (pointer)"nospc")
VectorInitElem (1, 43, 4, (pointer)"loop")
VectorInitElem (1, 52, 5, (pointer)"nfile")
VectorInitElem (1, 92, 1, (pointer)"]")
VectorInitElem (1, 48, 11, (pointer)"nametoolong")
VectorInitElem (1, 30, 5, (pointer)"dquot")
VectorInitElem (1, 112, 36, (pointer)"Top-level handler raised exception.\n")
VectorInitElem (1, 14, 9, (pointer)"addrinuse")
VectorInitElem (1, 18, 7, (pointer)"already")
VectorInitElem (1, 89, 6, (pointer)"txtbsy")
VectorInitElem (1, 90, 10, (pointer)"wouldblock")
VectorInitElem (1, 32, 5, (pointer)"fault")
VectorInitElem (1, 80, 9, (pointer)"prototype")
VectorInitElem (1, 111, 6, (pointer)"output")
VectorInitElem (1, 66, 5, (pointer)"nosys")
VectorInitElem (1, 73, 4, (pointer)"nxio")
VectorInitElem (1, 60, 5, (pointer)"nomem")
VectorInitElem (1, 22, 8, (pointer)"canceled")
VectorInitElem (1, 84, 4, (pointer)"srch")
VectorInitElem (1, 82, 4, (pointer)"rofs")
VectorInitElem (1, 58, 5, (pointer)"nolck")
VectorInitElem (1, 50, 8, (pointer)"netreset")
VectorInitElem (1, 37, 10, (pointer)"inprogress")
VectorInitElem (1, 31, 5, (pointer)"exist")
VectorInitElem (1, 61, 5, (pointer)"nomsg")
VectorInitElem (1, 119, 2, (pointer)" \"")
VectorInitElem (1, 126, 16, (pointer)"0123456789ABCDEF")
VectorInitElem (1, 109, 12, (pointer)"ClosedStream")
VectorInitElem (1, 97, 21, (pointer)"MLton.Exit.wrapSuffix")
VectorInitElem (1, 55, 5, (pointer)"nodev")
VectorInitElem (1, 71, 6, (pointer)"notsup")
VectorInitElem (1, 26, 9, (pointer)"connreset")
VectorInitElem (1, 24, 11, (pointer)"connaborted")
VectorInitElem (1, 75, 8, (pointer)"overflow")
VectorInitElem (1, 44, 5, (pointer)"mfile")
VectorInitElem (1, 56, 5, (pointer)"noent")
VectorInitElem (1, 79, 14, (pointer)"protonosupport")
VectorInitElem (1, 28, 11, (pointer)"destaddrreq")
VectorInitElem (1, 102, 36, (pointer)"unhandled exception in Basis Library")
VectorInitElem (1, 116, 13, (pointer)"Unknown error")
VectorInitElem (1, 87, 8, (pointer)"timedout")
VectorInitElem (1, 39, 5, (pointer)"inval")
VectorInitElem (1, 21, 4, (pointer)"busy")
VectorInitElem (1, 49, 7, (pointer)"netdown")
VectorInitElem (1, 101, 5, (pointer)"Fail ")
VectorInitElem (1, 19, 4, (pointer)"badf")
VectorInitElem (1, 106, 8, (pointer)"Overflow")
VectorInitElem (1, 40, 2, (pointer)"io")
VectorInitElem (1, 76, 4, (pointer)"perm")
VectorInitElem (1, 85, 5, (pointer)"stale")
VectorInitElem (1, 94, 13, (pointer)"partial write")
VectorInitElem (1, 83, 5, (pointer)"spipe")
VectorInitElem (1, 91, 4, (pointer)"xdev")
VectorInitElem (1, 29, 3, (pointer)"dom")
VectorInitElem (1, 125, 0, (pointer)"")
VectorInitElem (1, 53, 6, (pointer)"nobufs")
VectorInitElem (1, 105, 2, (pointer)"Io")
VectorInitElem (1, 108, 9, (pointer)"Subscript")
VectorInitElem (1, 54, 6, (pointer)"nodata")
VectorInitElem (1, 122, 9, (pointer)"<UNKNOWN>")
VectorInitElem (1, 57, 6, (pointer)"noexec")
VectorInitElem (1, 100, 21, (pointer)"unhandled exception: ")
VectorInitElem (1, 68, 6, (pointer)"notdir")
VectorInitElem (1, 51, 10, (pointer)"netunreach")
VectorInitElem (1, 96, 3, (pointer)"): ")
VectorInitElem (1, 88, 6, (pointer)"toobig")
VectorInitElem (1, 86, 4, (pointer)"time")
VectorInitElem (1, 74, 9, (pointer)"opnotsupp")
VectorInitElem (1, 70, 7, (pointer)"notsock")
VectorInitElem (1, 42, 5, (pointer)"isdir")
EndVectorInits
static void real_Init() {
}
static uint16_t frameOffsets0[] = {0};
static uint16_t frameOffsets1[] = {5,8,12,16,20,24};
static uint16_t frameOffsets2[] = {10,8,12,16,20,24,28,32,36,44,52};
static uint16_t frameOffsets3[] = {8,8,12,16,20,24,28,32,36};
static uint16_t frameOffsets4[] = {1,8};
static uint16_t frameOffsets5[] = {2,8,12};
static uint16_t frameOffsets6[] = {5,24,40,44,48,52};
static uint16_t frameOffsets7[] = {4,24,40,44,48};
static uint16_t frameOffsets8[] = {3,8,24,44};
static uint16_t frameOffsets9[] = {4,8,12,24,44};
static uint16_t frameOffsets10[] = {2,24,44};
static uint16_t frameOffsets11[] = {3,24,40,44};
static uint16_t frameOffsets12[] = {4,8,24,44,48};
static uint16_t frameOffsets13[] = {4,16,24,40,44};
static uint16_t frameOffsets14[] = {5,8,16,24,40,44};
static uint16_t frameOffsets15[] = {4,12,24,40,44};
static uint16_t frameOffsets16[] = {5,8,12,24,40,44};
static uint16_t frameOffsets17[] = {6,8,12,24,40,44,48};
static uint16_t frameOffsets18[] = {9,8,12,16,20,24,28,32,36,40};
static uint16_t frameOffsets19[] = {1,20};
static uint16_t frameOffsets20[] = {8,8,12,16,24,28,32,36,44};
static uint16_t frameOffsets21[] = {9,8,12,16,20,24,28,32,36,44};
static uint16_t frameOffsets22[] = {6,8,12,16,20,24,32};
static uint16_t frameOffsets23[] = {6,8,12,16,20,24,28};
static uint16_t frameOffsets24[] = {4,8,12,16,20};
static uint16_t frameOffsets25[] = {2,4,8};
static uint16_t frameOffsets26[] = {3,0,4,8};
static uint16_t frameOffsets27[] = {1,0};
static uint16_t frameOffsets28[] = {1,4};
static uint16_t frameOffsets29[] = {2,0,4};
static uint16_t frameOffsets30[] = {2,0,16};
static uint16_t frameOffsets31[] = {2,16,28};
static uint16_t frameOffsets32[] = {3,0,16,28};
static uint16_t frameOffsets33[] = {1,16};
static uint16_t frameOffsets34[] = {2,4,16};
static uint16_t frameOffsets35[] = {1,12};
static struct GC_frameLayout frameLayouts[] = {
	{C_FRAME, frameOffsets0, 4},
	{C_FRAME, frameOffsets0, 4},
	{ML_FRAME, frameOffsets0, 4},
	{C_FRAME, frameOffsets0, 4},
	{C_FRAME, frameOffsets1, 32},
	{C_FRAME, frameOffsets1, 32},
	{C_FRAME, frameOffsets2, 60},
	{C_FRAME, frameOffsets2, 60},
	{C_FRAME, frameOffsets2, 60},
	{C_FRAME, frameOffsets3, 44},
	{ML_FRAME, frameOffsets4, 16},
	{ML_FRAME, frameOffsets4, 16},
	{ML_FRAME, frameOffsets0, 12},
	{ML_FRAME, frameOffsets0, 4},
	{C_FRAME, frameOffsets5, 20},
	{ML_FRAME, frameOffsets6, 60},
	{ML_FRAME, frameOffsets7, 56},
	{ML_FRAME, frameOffsets8, 52},
	{ML_FRAME, frameOffsets0, 12},
	{ML_FRAME, frameOffsets0, 4},
	{ML_FRAME, frameOffsets0, 4},
	{C_FRAME, frameOffsets9, 52},
	{ML_FRAME, frameOffsets10, 52},
	{ML_FRAME, frameOffsets0, 4},
	{C_FRAME, frameOffsets11, 52},
	{ML_FRAME, frameOffsets0, 4},
	{C_FRAME, frameOffsets12, 56},
	{C_FRAME, frameOffsets13, 52},
	{C_FRAME, frameOffsets14, 52},
	{ML_FRAME, frameOffsets6, 60},
	{C_FRAME, frameOffsets15, 52},
	{C_FRAME, frameOffsets16, 52},
	{C_FRAME, frameOffsets17, 56},
	{C_FRAME, frameOffsets18, 48},
	{C_FRAME, frameOffsets3, 44},
	{C_FRAME, frameOffsets18, 48},
	{C_FRAME, frameOffsets0, 24},
	{C_FRAME, frameOffsets19, 28},
	{C_FRAME, frameOffsets0, 16},
	{C_FRAME, frameOffsets20, 52},
	{C_FRAME, frameOffsets21, 56},
	{C_FRAME, frameOffsets2, 68},
	{C_FRAME, frameOffsets2, 68},
	{C_FRAME, frameOffsets2, 68},
	{C_FRAME, frameOffsets0, 24},
	{C_FRAME, frameOffsets19, 28},
	{C_FRAME, frameOffsets0, 16},
	{C_FRAME, frameOffsets22, 40},
	{C_FRAME, frameOffsets23, 36},
	{C_FRAME, frameOffsets24, 28},
	{C_FRAME, frameOffsets1, 36},
	{C_FRAME, frameOffsets1, 40},
	{C_FRAME, frameOffsets0, 12},
	{ML_FRAME, frameOffsets25, 16},
	{C_FRAME, frameOffsets26, 16},
	{C_FRAME, frameOffsets27, 8},
	{ML_FRAME, frameOffsets28, 12},
	{C_FRAME, frameOffsets29, 12},
	{C_FRAME, frameOffsets28, 12},
	{C_FRAME, frameOffsets29, 12},
	{C_FRAME, frameOffsets29, 12},
	{C_FRAME, frameOffsets25, 16},
	{C_FRAME, frameOffsets29, 20},
	{C_FRAME, frameOffsets27, 8},
	{C_FRAME, frameOffsets30, 32},
	{C_FRAME, frameOffsets31, 36},
	{ML_FRAME, frameOffsets0, 20},
	{C_FRAME, frameOffsets32, 36},
	{C_FRAME, frameOffsets31, 36},
	{C_FRAME, frameOffsets33, 28},
	{ML_FRAME, frameOffsets34, 24},
	{C_FRAME, frameOffsets34, 24},
	{ML_FRAME, frameOffsets0, 12},
	{ML_FRAME, frameOffsets34, 24},
	{C_FRAME, frameOffsets34, 24},
	{ML_FRAME, frameOffsets0, 12},
	{C_FRAME, frameOffsets34, 24},
	{C_FRAME, frameOffsets28, 20},
	{C_FRAME, frameOffsets0, 16},
	{C_FRAME, frameOffsets35, 20},
	{C_FRAME, frameOffsets0, 8},
	{C_FRAME, frameOffsets0, 16},
	{C_FRAME, frameOffsets35, 20},
	{C_FRAME, frameOffsets0, 8},
	{C_FRAME, frameOffsets29, 12},
	{C_FRAME, frameOffsets0, 16},
	{C_FRAME, frameOffsets35, 20},
	{C_FRAME, frameOffsets0, 8},
	{C_FRAME, frameOffsets0, 16},
	{C_FRAME, frameOffsets35, 20},
	{C_FRAME, frameOffsets0, 8},
	{C_FRAME, frameOffsets27, 8},
};
static struct GC_objectType objectTypes[] = {
	{ STACK_TAG, FALSE, 0, 0 },
	{ NORMAL_TAG, TRUE, 8, 1 },
	{ WEAK_TAG, FALSE, 8, 0 },
	{ SEQUENCE_TAG, FALSE, 1, 0 },
	{ SEQUENCE_TAG, FALSE, 4, 0 },
	{ SEQUENCE_TAG, FALSE, 2, 0 },
	{ SEQUENCE_TAG, FALSE, 8, 0 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, FALSE, 8, 0 },
	{ NORMAL_TAG, TRUE, 4, 0 },
	{ SEQUENCE_TAG, TRUE, 1, 0 },
	{ NORMAL_TAG, TRUE, 8, 0 },
	{ NORMAL_TAG, TRUE, 4, 0 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 3 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, TRUE, 0, 0 },
	{ NORMAL_TAG, FALSE, 0, 4 },
	{ NORMAL_TAG, FALSE, 4, 1 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, FALSE, 12, 0 },
	{ SEQUENCE_TAG, TRUE, 4, 0 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, FALSE, 0, 3 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 1 },
	{ NORMAL_TAG, FALSE, 0, 1 },
	{ NORMAL_TAG, FALSE, 4, 1 },
	{ NORMAL_TAG, FALSE, 0, 3 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
};
static uint32_t* sourceSeqs[] = {
};
static GC_sourceSeqIndex frameSources[] = {
};
static struct GC_sourceLabel sourceLabels[] = {
};
static char* sourceNames[] = {
};
static struct GC_source sources[] = {
};
static char* atMLtons[] = {
	"@MLton",
	"--",
};
DeclareChunk (0);
PRIVATE struct cont ( *nextChunks []) () = {	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
	Chunkp (0),
};
MLtonMain (4, 0xC67B32B, 68, TRUE, PROFILE_NONE, FALSE, 0, 98)
#include <rtems.h>
#include <stdlib.h>
#include <stdio.h>
rtems_task Init(
rtems_task_argument ignored
)
{
char* argv[0];
MLton_main (0, argv);
exit (0);
}
/* Ad-hoc configuration from rtems examples
 * The default max number of file descriptors in rtems is 3,
 * so in order to open files other than stdout/err/in, we set the max to 10. */
#define CONFIGURE_RTEMS_INIT_TASKS_TABLE
#define CONFIGURE_UNIFIED_WORK_AREAS
#define CONFIGURE_STACK_CHECKER_ENABLED

/* on smaller architectures lower the number or resources */
#if defined(__m32c__)
  #define CONFIGURE_MAXIMUM_TASKS 3
#else
  #define CONFIGURE_UNLIMITED_OBJECTS
  #define CONFIGURE_MAXIMUM_USER_EXTENSIONS 8
  #define CONFIGURE_MAXIMUM_DRIVERS 16
  #define CONFIGURE_LIBIO_MAXIMUM_FILE_DESCRIPTORS 32
#endif

/* Include basic device drivers needed to call delays */
#define CONFIGURE_APPLICATION_NEEDS_CLOCK_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_CONSOLE_DRIVER

#define CONFIGURE_SMP_APPLICATION

#define CONFIGURE_SMP_MAXIMUM_PROCESSORS 32

#define CONFIGURE_INIT
#include <rtems/confdefs.h>
