/* MLton g0b5910a-dirty (built Thu Nov 30 01:30:50 EST 2017 on oem-virtual-machine) */
/*   created this file on Thu Dec 07 01:13:14 2017. */
/* Do not edit this file. */
/* Flag settings:  */
/*    align: 8 */
/*    atMLtons: (@MLton, --) */
/*    chunk: coalesce 4096 */
/*    closureConvertGlobalize: true */
/*    closureConvertShrink: true */
/*    codegen: sparc-rtems4.11 */
/*    contifyIntoMain: false */
/*    debug: false */
/*    defaultChar: char8 */
/*    defaultWideChar: widechar32 */
/*    defaultInt: int32 */
/*    defaultReal: real64 */
/*    defaultWord: word32 */
/*    diag passes: [] */
/*    drop passes: [] */
/*    elaborate allowConstant (default): false */
/*    elaborate allowConstant (enabled): true */
/*    elaborate allowFFI (default): false */
/*    elaborate allowFFI (enabled): true */
/*    elaborate allowPrim (default): false */
/*    elaborate allowPrim (enabled): true */
/*    elaborate allowOverload (default): false */
/*    elaborate allowOverload (enabled): true */
/*    elaborate allowOptBar (default): false */
/*    elaborate allowOptBar (enabled): true */
/*    elaborate allowOptSemicolon (default): false */
/*    elaborate allowOptSemicolon (enabled): true */
/*    elaborate allowLineComments (default): false */
/*    elaborate allowLineComments (enabled): true */
/*    elaborate allowDoDecls (default): false */
/*    elaborate allowDoDecls (enabled): true */
/*    elaborate allowRecPunning (default): false */
/*    elaborate allowRecPunning (enabled): true */
/*    elaborate allowOrPats (default): false */
/*    elaborate allowOrPats (enabled): true */
/*    elaborate allowExtendedLiterals (default): false */
/*    elaborate allowExtendedLiterals (enabled): true */
/*    elaborate allowSigWithtype (default): false */
/*    elaborate allowSigWithtype (enabled): true */
/*    elaborate allowRebindEquals (default): false */
/*    elaborate allowRebindEquals (enabled): true */
/*    elaborate deadCode (default): false */
/*    elaborate deadCode (enabled): true */
/*    elaborate forceUsed (default): false */
/*    elaborate forceUsed (enabled): true */
/*    elaborate ffiStr (default):  */
/*    elaborate ffiStr (enabled): true */
/*    elaborate nonexhaustiveExnMatch (default): default */
/*    elaborate nonexhaustiveExnMatch (enabled): true */
/*    elaborate nonexhaustiveMatch (default): warn */
/*    elaborate nonexhaustiveMatch (enabled): true */
/*    elaborate redundantMatch (default): warn */
/*    elaborate redundantMatch (enabled): true */
/*    elaborate resolveScope (default): strdec */
/*    elaborate resolveScope (enabled): true */
/*    elaborate sequenceNonUnit (default): ignore */
/*    elaborate sequenceNonUnit (enabled): true */
/*    elaborate valrecConstr (default): warn */
/*    elaborate valrecConstr (enabled): true */
/*    elaborate warnUnused (default): false */
/*    elaborate warnUnused (enabled): true */
/*    elaborate only: false */
/*    emit main: true */
/*    export header: None */
/*    exn history: false */
/*    generated output format: executable */
/*    gc check: Limit */
/*    indentation: 3 */
/*    inlineIntoMain: true */
/*    inlineLeafA: {loops = true, repeat = true, size = Some 20} */
/*    inlineLeafB: {loops = true, repeat = true, size = Some 40} */
/*    inlineNonRec: {small = 60, product = 320} */
/*    input file: kitfib35 */
/*    keep AST: false */
/*    keep CoreML: false */
/*    keep def use: true */
/*    keep dot: false */
/*    keep Machine: false */
/*    keep passes: [] */
/*    keep RSSA: false */
/*    keep SSA: false */
/*    keep SSA2: false */
/*    keep SXML: false */
/*    keep XML: false */
/*    extra_: false */
/*    lib dir: /home/oem/pickle/take2/X86/build/lib */
/*    lib target dir: /home/oem/pickle/take2/X86/build/lib/targets/sparc-rtems4.11 */
/*    loop passes: 1 */
/*    mark cards: true */
/*    max function size: 10000 */
/*    mlb path vars: [{var = MLTON_ROOT, path = $(LIB_MLTON_DIR)/sml}, {var = SML_LIB, path = $(LIB_MLTON_DIR)/sml}] */
/*    native commented: 0 */
/*    native live stack: false */
/*    native optimize: 1 */
/*    native move hoist: true */
/*    native copy prop: true */
/*    native copy prop cutoff: 1000 */
/*    native cutoff: 100 */
/*    native live transfer: 8 */
/*    native shuffle: true */
/*    native ieee fp: false */
/*    native split: Some 20000 */
/*    optimizationPasses: [<ssa2::default>, <ssa::default>, <sxml::default>, <xml::default>] */
/*    polyvariance: Some {hofo = true, rounds = 2, small = 30, product = 300} */
/*    prefer abs paths: false */
/*    prof passes: [] */
/*    profile: None */
/*    profile branch: false */
/*    profile C: [] */
/*    profile IL: ProfileSource */
/*    profile include/exclude: [(Seq [Star [.], Or [Seq [Seq [[$], [(], [S], [M], [L], [_], [L], [I], [B], [)]]]], Star [.]], false)] */
/*    profile raise: false */
/*    profile stack: false */
/*    profile val: false */
/*    show basis: None */
/*    show def-use: None */
/*    show types: true */
/*    target: sparc-rtems4.11 */
/*    target arch: Sparc */
/*    target OS: Rtems */
/*    type check: false */
/*    verbosity: Pass */
/*    warn unrecognized annotation: true */
/*    warn deprecated features: true */
/*    zone cut depth: 100 */
#define _ISOC99_SOURCE
#include <c-chunk.h>

#define ExnStackOffset 16
#define FrontierOffset 0
#define StackBottomOffset 580
#define StackTopOffset 8
PRIVATE extern struct GC_state gcState;
PRIVATE extern CPointer globalCPointer [0];
PRIVATE extern CPointer CReturnQ;
PRIVATE extern Int8 globalInt8 [0];
PRIVATE extern Int8 CReturnI8;
PRIVATE extern Int16 globalInt16 [0];
PRIVATE extern Int16 CReturnI16;
PRIVATE extern Int32 globalInt32 [0];
PRIVATE extern Int32 CReturnI32;
PRIVATE extern Int64 globalInt64 [0];
PRIVATE extern Int64 CReturnI64;
PRIVATE extern Objptr globalObjptr [16];
PRIVATE extern Objptr CReturnP;
PRIVATE extern Real32 globalReal32 [0];
PRIVATE extern Real32 CReturnR32;
PRIVATE extern Real64 globalReal64 [0];
PRIVATE extern Real64 CReturnR64;
PRIVATE extern Word8 globalWord8 [0];
PRIVATE extern Word8 CReturnW8;
PRIVATE extern Word16 globalWord16 [0];
PRIVATE extern Word16 CReturnW16;
PRIVATE extern Word32 globalWord32 [6];
PRIVATE extern Word32 CReturnW32;
PRIVATE extern Word64 globalWord64 [0];
PRIVATE extern Word64 CReturnW64;
PRIVATE extern Pointer globalObjptrNonRoot [1];
PRIVATE void GC_collect (CPointer x2, Word32 x1, Int32 x0);
PRIVATE Objptr GC_arrayAllocate (CPointer x3, Word32 x2, Int32 x1, Word32 x0);
PRIVATE void MLton_halt (CPointer x1, Int32 x0);
PRIVATE void Stdio_print (Objptr x0);
PRIVATE void MLton_bug (Objptr x0);
DeclareChunk (0);
Chunk (0)
	CPointer Q_0;
	CPointer Q_1;
	CPointer Q_2;
	CPointer Q_3;
	CPointer Q_4;
	CPointer Q_5;
	CPointer Q_6;
	CPointer Q_7;
	CPointer Q_8;
	CPointer Q_9;
	CPointer Q_10;
	CPointer Q_11;
	CPointer Q_12;
	CPointer Q_13;
	CPointer Q_14;
	CPointer Q_15;
	CPointer Q_16;
	CPointer Q_17;
	CPointer Q_18;
	CPointer Q_19;
	CPointer Q_20;
	Objptr P_0;
	Objptr P_1;
	Objptr P_2;
	Objptr P_3;
	Objptr P_4;
	Objptr P_5;
	Word8 W8_0;
	Word8 W8_1;
	Word8 W8_2;
	Word16 W16_0;
	Word16 W16_1;
	Word32 W32_0;
	Word32 W32_1;
	Word32 W32_2;
	Word32 W32_3;
	Word32 W32_4;
	Word32 W32_5;
	Word32 W32_6;
	Word32 W32_7;
	Word32 W32_8;
	Word32 W32_9;
ChunkSwitch (0)
case 29:
L_168:
	Push (-8);
L_123:
switch ((Word32)S(Objptr, 0)) {
case (Word32)(0x1ull):
	O(Word32, G(Objptr, 3), -4) = (Word32)(0x7ull);
	S(Objptr, 0) = (Objptr)G(Objptr, 3);
	Return ();
default:
	P_0 = O(Objptr, S(Objptr, 0), 8);
	P_1 = O(Objptr, S(Objptr, 0), 4);
	S(Objptr, 0) = P_0;
	S(Objptr, 4) = P_1;
	S(Objptr, 8) = (Objptr)(Word32)(0x1ull);
L_125:
	W32_0 = CPointer_lt (O(CPointer, GCState, 4), Frontier);
	BNZ (W32_0, L_164);
L_126:
	W32_0 = O(Word32, S(Objptr, 4), -8);
	C(Word32, Frontier) = (Word32)(0xFull);
	Q_19 = CPointer_add (Frontier, (Word32)(0x4ull));
	P_0 = (Objptr)Q_19;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	O(Word32, P_0, 0) = W32_0;
	O(Word32, P_0, 4) = (Word32)(Word32)(0x0ull);
	O(Objptr, P_0, 8) = S(Objptr, 4);
	C(Word32, Frontier) = (Word32)(0x21ull);
	Q_18 = CPointer_add (Frontier, (Word32)(0x4ull));
	P_1 = (Objptr)Q_18;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	O(Word32, P_1, 0) = (Word32)(Word32)(0x0ull);
	O(Objptr, P_1, 4) = P_0;
	O(Objptr, P_1, 8) = S(Objptr, 8);
switch ((Word32)S(Objptr, 0)) {
case (Word32)(0x1ull):
	S(Objptr, 0) = S(Objptr, 8);
	S(Objptr, 4) = P_0;
	S(Objptr, 8) = (Objptr)(Word32)(0x1ull);
L_129:
	W32_0 = CPointer_lt (O(CPointer, GCState, 4), Frontier);
	BNZ (W32_0, L_162);
L_130:
	C(Word32, Frontier) = (Word32)(0x21ull);
	Q_20 = CPointer_add (Frontier, (Word32)(0x4ull));
	P_0 = (Objptr)Q_20;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	O(Word32, P_0, 0) = (Word32)(Word32)(0x0ull);
	O(Objptr, P_0, 4) = S(Objptr, 4);
	O(Objptr, P_0, 8) = S(Objptr, 8);
switch ((Word32)S(Objptr, 0)) {
case (Word32)(0x1ull):
switch ((Word32)S(Objptr, 8)) {
case (Word32)(0x1ull):
	S(Objptr, 8) = O(Objptr, S(Objptr, 4), 8);
	S(Word32, 12) = O(Word32, S(Objptr, 4), 0);
	W32_0 = O(Word32, S(Objptr, 8), -8);
	W32_1 = Word32_equal (S(Word32, 12), W32_0);
	BNZ (W32_1, L_161);
	W32_0 = Word32_equal (S(Word32, 12), (Word32)(0x0ull));
	BNZ (W32_0, L_160);
	W32_0 = WordU32_lt ((Word32)(0x7FFFFFFFull), S(Word32, 12));
	BNZ (W32_0, L_159);
	{
	Word32 tmp0 = S(Word32, 12);
	S(CPointer, 20) = 24;
	Push (24);
	FlushFrontier();
	FlushStackTop();
	CReturnP = GC_arrayAllocate (GCState, (Word32)(0x0ull), tmp0, (Word32)(0x11ull));
	}
	CacheFrontier();
	CacheStackTop();
L_155:
	Push (-24);
	P_0 = CReturnP;
L_156:
	W32_0 = (Word32)(0x0ull);
loop_11:
	W32_1 = WordS32_lt (W32_0, S(Word32, 12));
	BNZ (W32_1, L_158);
	O(Word32, P_0, -4) = (Word32)(0x7ull);
	S(Objptr, 0) = (Objptr)P_0;
	Return ();
L_158:
	W8_0 = X(Word8, S(Objptr, 8), W32_0, 1, 0);
	X(Word8, P_0, W32_0, 1, 0) = W8_0;
	W32_1 = Word32_add (W32_0, (Word32)(0x1ull));
	W32_0 = W32_1;
	goto loop_11;
L_159:
	Raise ();
L_160:
	P_0 = G(Objptr, 2);
	goto L_156;
L_161:
	S(Objptr, 0) = S(Objptr, 8);
	Return ();
default:
	P_0 = S(Objptr, 8);
	P_1 = S(Objptr, 4);
	W32_0 = (Word32)(0x0ull);
L_134:
	W32_1 = O(Word32, P_1, 0);
	WordS32_addCheck (S(Word32, 12), W32_0, W32_1, L_135);
switch ((Word32)P_0) {
case (Word32)(0x1ull):
	W32_0 = Word32_equal (S(Word32, 12), (Word32)(0x0ull));
	BNZ (W32_0, L_150);
	W32_0 = WordU32_lt ((Word32)(0x7FFFFFFFull), S(Word32, 12));
	BNZ (W32_0, L_149);
	{
	Word32 tmp0 = S(Word32, 12);
	S(CPointer, 20) = 26;
	Push (24);
	FlushFrontier();
	FlushStackTop();
	CReturnP = GC_arrayAllocate (GCState, (Word32)(0x0ull), tmp0, (Word32)(0x11ull));
	}
	CacheFrontier();
	CacheStackTop();
L_141:
	Push (-24);
	P_0 = CReturnP;
L_142:
	P_1 = S(Objptr, 8);
	P_2 = S(Objptr, 4);
	W32_0 = (Word32)(0x0ull);
	W32_1 = (Word32)(0x0ull);
loop_9:
	W32_2 = WordS32_lt (W32_1, S(Word32, 12));
	BNZ (W32_2, L_144);
	O(Word32, P_0, -4) = (Word32)(0x7ull);
	S(Objptr, 0) = (Objptr)P_0;
	Return ();
L_144:
loop_10:
	W32_2 = O(Word32, P_2, 0);
	W32_3 = WordS32_lt (W32_0, W32_2);
	BNZ (W32_3, L_148);
switch ((Word32)P_1) {
case (Word32)(0x1ull):
	Raise ();
default:
	P_2 = O(Objptr, P_1, 8);
	P_3 = O(Objptr, P_1, 4);
	P_1 = P_2;
	P_2 = P_3;
	W32_0 = (Word32)(0x0ull);
	goto loop_10;
}
L_148:
	P_3 = O(Objptr, P_2, 8);
	W8_0 = X(Word8, P_3, W32_0, 1, 0);
	W32_2 = Word32_add (W32_0, (Word32)(0x1ull));
	X(Word8, P_0, W32_1, 1, 0) = W8_0;
	W32_3 = Word32_add (W32_1, (Word32)(0x1ull));
	W32_0 = W32_2;
	W32_1 = W32_3;
	goto loop_9;
L_149:
	Raise ();
L_150:
	P_0 = G(Objptr, 1);
	goto L_142;
default:
	P_1 = O(Objptr, P_0, 8);
	P_2 = O(Objptr, P_0, 4);
	P_0 = P_1;
	P_1 = P_2;
	W32_0 = S(Word32, 12);
	goto L_134;
}
L_135:
	Raise ();
}
default:
	P_1 = O(Objptr, S(Objptr, 0), 8);
	P_2 = O(Objptr, S(Objptr, 0), 4);
	S(Objptr, 0) = P_1;
	S(Objptr, 4) = P_2;
	S(Objptr, 8) = P_0;
	goto L_129;
}
L_162:
	S(CPointer, 12) = 27;
	Push (16);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
L_163:
	Push (-16);
	goto L_130;
default:
	P_0 = O(Objptr, S(Objptr, 0), 8);
	P_2 = O(Objptr, S(Objptr, 0), 4);
	S(Objptr, 0) = P_0;
	S(Objptr, 4) = P_2;
	S(Objptr, 8) = P_1;
	goto L_125;
}
L_164:
	S(CPointer, 12) = 28;
	Push (16);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
L_165:
	Push (-16);
	goto L_126;
}
case 28:
	goto L_165;
case 27:
	goto L_163;
case 24:
	goto L_155;
case 26:
	goto L_141;
case 30:
concat_0:
	W32_0 = CPointer_lt (O(CPointer, GCState, 12), StackTop);
	BNZ (W32_0, L_167);
	goto L_123;
L_167:
	S(CPointer, 4) = 29;
	Push (8);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
	goto L_168;
case 4:
L_121:
	Push (-8);
L_112:
	W32_0 = WordS32_lt (S(Word32, 0), (Word32)(0x1ull));
	BNZ (W32_0, L_119);
	W32_0 = Word32_sub (S(Word32, 0), (Word32)(0x1ull));
	S(Word32, 8) = W32_0;
	S(CPointer, 4) = 5;
	Push (8);
fib_0:
	W32_0 = CPointer_lt (O(CPointer, GCState, 12), StackTop);
	BNZ (W32_0, L_120);
	goto L_112;
L_120:
	S(CPointer, 4) = 4;
	Push (8);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
	goto L_121;
L_119:
	S(Word32, 0) = (Word32)(0x1ull);
	Return ();
case 25:
	Push (-16);
	S(Word32, 8) = S(Word32, 16);
	WordS32_addCheck (W32_0, S(Word32, 4), S(Word32, 8), L_115);
	S(Word32, 0) = W32_0;
	Return ();
L_115:
	GPNR(0) = (Objptr)(Word32)(0x1ull);
	Raise ();
case 5:
	Push (-8);
	S(Word32, 4) = S(Word32, 8);
	WordS32_subCheckXC (W32_0, S(Word32, 0), (Word32)(0x2ull), L_115);
	S(Word32, 16) = W32_0;
	S(CPointer, 12) = 25;
	Push (16);
	goto fib_0;
case 31:
	goto fib_0;
case 22:
L_110:
	Push (-16);
L_10:
	S(Objptr, 8) = G(Objptr, 0);
	S(Word32, 12) = (Word32)(0x1ull);
	S(Word32, 16) = (Word32)(0x40000000ull);
loop_0:
	W32_0 = CPointer_lt (O(CPointer, GCState, 4), Frontier);
	BNZ (W32_0, L_107);
L_11:
	W32_0 = Word32_equal (S(Word32, 16), (Word32)(0x0ull));
	BNZ (W32_0, L_19);
	WordS32_addCheckXC (W32_0, S(Word32, 12), (Word32)(0x1ull), L_13);
	C(Word32, Frontier) = (Word32)(0x23ull);
	Q_4 = CPointer_add (Frontier, (Word32)(0x4ull));
	P_0 = (Objptr)Q_4;
	Frontier = CPointer_add (Frontier, (Word32)(0x8ull));
	O(Objptr, P_0, 0) = S(Objptr, 8);
	S(Objptr, 8) = P_0;
	S(Word32, 12) = W32_0;
	S(Word32, 16) = (Word32)(0x0ull);
	goto loop_0;
L_13:
	Stdio_print (G(Objptr, 9));
	Stdio_print (G(Objptr, 10));
	Stdio_print (G(Objptr, 7));
	MLton_bug (G(Objptr, 11));
	Return ();
L_19:
switch ((Word32)S(Objptr, 8)) {
case (Word32)(0x1ull):
L_24:
	C(Word32, Frontier) = (Word32)(0x13ull);
	Q_5 = CPointer_add (Frontier, (Word32)(0x4ull));
	S(Objptr, 8) = (Objptr)Q_5;
	Frontier = CPointer_add (Frontier, (Word32)(0x8ull));
	O(Objptr, S(Objptr, 8), 0) = (Objptr)(Word32)(0x1ull);
	W32_0 = (Word32)(0x0ull);
loop_2:
	W32_1 = WordS32_lt (W32_0, (Word32)(0x100ull));
	BNZ (W32_1, L_103);
	W32_0 = (Word32)(0x0ull);
loop_3:
	W32_1 = WordS32_lt (W32_0, (Word32)(0x100ull));
	BNZ (W32_1, L_102);
	W32_0 = (Word32)(0x0ull);
loop_4:
	W32_1 = WordS32_lt (W32_0, (Word32)(0x100ull));
	BNZ (W32_1, L_101);
	W32_0 = (Word32)(0x0ull);
loop_5:
	W32_1 = WordS32_lt (W32_0, (Word32)(0x100ull));
	BNZ (W32_1, L_91);
	W32_0 = (Word32)(0x0ull);
loop_6:
	W32_1 = WordS32_lt (W32_0, (Word32)(0x100ull));
	BNZ (W32_1, L_90);
	S(CPointer, 12) = 7;
	Push (16);
	FlushFrontier();
	FlushStackTop();
	CReturnP = GC_arrayAllocate (GCState, (Word32)(0x0ull), (Word32)(0x21ull), (Word32)(0x11ull));
	CacheFrontier();
	CacheStackTop();
L_30:
	Push (-16);
	S(Objptr, 12) = CReturnP;
	W32_0 = (Word32)(0x0ull);
loop_7:
	W32_1 = WordS32_lt (W32_0, (Word32)(0x21ull));
	BNZ (W32_1, L_89);
	W32_0 = CPointer_lt (O(CPointer, GCState, 4), Frontier);
	BNZ (W32_0, L_87);
L_32:
	C(Word32, Frontier) = (Word32)(0x15ull);
	Q_7 = CPointer_add (Frontier, (Word32)(0x4ull));
	P_0 = (Objptr)Q_7;
	Frontier = CPointer_add (Frontier, (Word32)(0x8ull));
	O(Word32, P_0, 0) = (Word32)(0x0ull);
	C(Word32, Frontier) = (Word32)(0x17ull);
	Q_6 = CPointer_add (Frontier, (Word32)(0x4ull));
	S(Objptr, 16) = (Objptr)Q_6;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	O(Word32, S(Objptr, 16), 0) = (Word32)(Word32)(0x0ull);
	O(Objptr, S(Objptr, 16), 4) = P_0;
	O(Objptr, S(Objptr, 16), 8) = S(Objptr, 12);
	W32_0 = (Word32)(0x0ull);
loop_8:
	W32_1 = WordS32_lt (W32_0, (Word32)(0x1ull));
	BNZ (W32_1, L_86);
	W32_0 = CPointer_lt (O(CPointer, GCState, 4), Frontier);
	BNZ (W32_0, L_84);
L_34:
	P_0 = O(Objptr, S(Objptr, 8), 0);
	C(Word32, Frontier) = (Word32)(0x1Bull);
	Q_13 = CPointer_add (Frontier, (Word32)(0x4ull));
	P_1 = (Objptr)Q_13;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	W32_0 = WordU8_extdToWord32 ((Word8)(Word8)(0x1ull));
	W32_1 = Word32_lshift (W32_0, (Word32)(0x18ull));
	O(Word32, P_1, 0) = (Word32)W32_1;
	O(Word32, P_1, 4) = (Word32)(Word32)(0x0ull);
	O(Objptr, P_1, 8) = P_0;
	W32_2 = WordU32_rshift ((Word32)S(Objptr, 8), (Word32)(0x8ull));
	X(Word8, O(CPointer, GCState, 352), W32_2, 1, 0) = (Word8)(0x1ull);
	O(Objptr, S(Objptr, 8), 0) = P_1;
	P_2 = O(Objptr, S(Objptr, 8), 0);
	C(Word32, Frontier) = (Word32)(0x1Bull);
	Q_12 = CPointer_add (Frontier, (Word32)(0x4ull));
	P_3 = (Objptr)Q_12;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	W32_3 = WordU8_extdToWord32 ((Word8)(Word8)(0x2ull));
	W32_4 = Word32_lshift (W32_3, (Word32)(0x18ull));
	O(Word32, P_3, 0) = (Word32)W32_4;
	O(Word32, P_3, 4) = (Word32)(Word32)(0x0ull);
	O(Objptr, P_3, 8) = P_2;
	W32_5 = WordU32_rshift ((Word32)S(Objptr, 8), (Word32)(0x8ull));
	X(Word8, O(CPointer, GCState, 352), W32_5, 1, 0) = (Word8)(0x1ull);
	O(Objptr, S(Objptr, 8), 0) = P_3;
	P_4 = O(Objptr, S(Objptr, 8), 0);
	C(Word32, Frontier) = (Word32)(0x1Bull);
	Q_11 = CPointer_add (Frontier, (Word32)(0x4ull));
	P_5 = (Objptr)Q_11;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	W32_6 = WordU8_extdToWord32 ((Word8)(Word8)(0x0ull));
	W32_7 = Word32_lshift (W32_6, (Word32)(0x18ull));
	O(Word32, P_5, 0) = (Word32)W32_7;
	O(Word32, P_5, 4) = (Word32)(Word32)(0x0ull);
	O(Objptr, P_5, 8) = P_4;
	W32_8 = WordU32_rshift ((Word32)S(Objptr, 8), (Word32)(0x8ull));
	X(Word8, O(CPointer, GCState, 352), W32_8, 1, 0) = (Word8)(0x1ull);
	O(Objptr, S(Objptr, 8), 0) = P_5;
	C(Word32, Frontier) = (Word32)(0x15ull);
	Q_10 = CPointer_add (Frontier, (Word32)(0x4ull));
	S(Objptr, 12) = (Objptr)Q_10;
	Frontier = CPointer_add (Frontier, (Word32)(0x8ull));
	O(Word32, S(Objptr, 12), 0) = (Word32)(0x0ull);
	C(Word32, Frontier) = (Word32)(0x19ull);
	Q_9 = CPointer_add (Frontier, (Word32)(0x4ull));
	S(Objptr, 20) = (Objptr)Q_9;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	O(Word32, S(Objptr, 20), 0) = (Word32)(Word32)(0x0ull);
	O(Objptr, S(Objptr, 20), 4) = S(Objptr, 16);
	O(Objptr, S(Objptr, 20), 8) = S(Objptr, 12);
	S(CPointer, 0) = 9;
	Q_8 = CPointer_add (StackTop, (Word32)(0x4ull));
	W32_9 = CPointer_diff (Q_8, O(CPointer, GCState, 580));
	O(Word32, GCState, 16) = (Word32)W32_9;
	S(Word32, 32) = (Word32)(0x23ull);
	S(CPointer, 28) = 8;
	Push (32);
	goto fib_0;
L_84:
	S(CPointer, 20) = 19;
	Push (24);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
L_85:
	Push (-24);
	goto L_34;
L_86:
	W32_1 = Word32_add (W32_0, (Word32)(0x1ull));
	W32_0 = W32_1;
	goto loop_8;
L_87:
	S(CPointer, 20) = 20;
	Push (24);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
L_88:
	Push (-24);
	goto L_32;
L_89:
	X(Word8, S(Objptr, 12), W32_0, 1, 0) = (Word8)(0x0ull);
	W32_1 = Word32_add ((Word32)(0x1ull), W32_0);
	W32_0 = W32_1;
	goto loop_7;
L_90:
	W32_1 = Word32_add (W32_0, (Word32)(0x1ull));
	W32_0 = W32_1;
	goto loop_6;
L_91:
	W8_0 = WordU32_extdToWord8 (W32_0);
	P_0 = G(Objptr, 5);
	W16_0 = (Word16)(Word16)(0x3930ull);
L_92:
	W16_1 = WordU16_rshift (W16_0, (Word32)(0x8ull));
	W8_1 = WordU16_extdToWord8 (W16_1);
	W8_2 = WordU16_extdToWord8 (W16_0);
	W32_1 = WordU8_lt (W8_0, W8_2);
	BNZ (W32_1, L_100);
	W32_1 = WordU8_lt (W8_1, W8_0);
	BNZ (W32_1, L_96);
L_95:
	W32_1 = Word32_add (W32_0, (Word32)(0x1ull));
	W32_0 = W32_1;
	goto loop_5;
L_96:
L_97:
switch ((Word32)P_0) {
case (Word32)(0x1ull):
	goto L_95;
default:
	P_1 = O(Objptr, P_0, 8);
	W16_0 = O(Word16, P_0, 0);
	P_0 = P_1;
	goto L_92;
}
L_100:
	goto L_97;
L_101:
	W32_1 = Word32_add (W32_0, (Word32)(0x1ull));
	W32_0 = W32_1;
	goto loop_4;
L_102:
	W32_1 = Word32_add (W32_0, (Word32)(0x1ull));
	W32_0 = W32_1;
	goto loop_3;
L_103:
	W32_1 = Word32_add ((Word32)(0x1ull), W32_0);
	W32_0 = W32_1;
	goto loop_2;
default:
	P_0 = O(Objptr, S(Objptr, 8), 0);
loop_1:
switch ((Word32)P_0) {
case (Word32)(0x1ull):
	W32_0 = CPointer_lt (O(CPointer, GCState, 4), Frontier);
	BNZ (W32_0, L_104);
L_23:
	goto L_24;
L_104:
	S(CPointer, 12) = 21;
	Push (16);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
L_105:
	Push (-16);
	goto L_23;
default:
	P_1 = O(Objptr, P_0, 0);
	P_0 = P_1;
	goto loop_1;
}
}
L_107:
	S(CPointer, 20) = 23;
	Push (24);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
L_108:
	Push (-24);
	goto L_11;
case 23:
	goto L_108;
case 21:
	goto L_105;
case 20:
	goto L_88;
case 19:
	goto L_85;
case 18:
L_83:
	Push (-32);
L_40:
	P_0 = O(Objptr, S(Objptr, 8), 0);
switch ((Word32)P_0) {
case (Word32)(0x1ull):
L_47:
switch ((Word32)S(Objptr, 12)) {
case (Word32)(0x1ull):
	P_0 = G(Objptr, 10);
L_49:
	C(Word32, Frontier) = (Word32)(0x1Full);
	Q_15 = CPointer_add (Frontier, (Word32)(0x4ull));
	P_1 = (Objptr)Q_15;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	O(Word32, P_1, 0) = (Word32)(Word32)(0x0ull);
	O(Objptr, P_1, 4) = P_0;
	O(Objptr, P_1, 8) = G(Objptr, 6);
	C(Word32, Frontier) = (Word32)(0x1Full);
	Q_14 = CPointer_add (Frontier, (Word32)(0x4ull));
	P_2 = (Objptr)Q_14;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	O(Word32, P_2, 0) = (Word32)(Word32)(0x0ull);
	O(Objptr, P_2, 4) = G(Objptr, 9);
	O(Objptr, P_2, 8) = P_1;
	S(CPointer, 0) = 10;
	S(Objptr, 32) = P_2;
	S(CPointer, 28) = 11;
	Push (32);
	goto concat_0;
default:
	P_0 = G(Objptr, 13);
	goto L_49;
}
default:
	P_1 = O(Objptr, P_0, 8);
	W8_0 = O(Word8, P_0, 0);
	P_0 = P_1;
L_42:
switch (W8_0) {
case (Word8)(0x1ull):
	W32_0 = Word32_andb ((Word32)S(Objptr, 12), (Word32)(0x3ull));
switch (W32_0) {
case (Word32)(0x0ull):
	W32_0 = CPointer_lt (O(CPointer, GCState, 4), Frontier);
	BNZ (W32_0, L_73);
L_68:
	C(Word32, Frontier) = (Word32)(0x1Full);
	Q_17 = CPointer_add (Frontier, (Word32)(0x4ull));
	P_0 = (Objptr)Q_17;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	O(Word32, P_0, 0) = (Word32)(Word32)(0x0ull);
	O(Objptr, P_0, 4) = S(Objptr, 12);
	O(Objptr, P_0, 8) = (Objptr)(Word32)(0x1ull);
	C(Word32, Frontier) = (Word32)(0x1Full);
	Q_16 = CPointer_add (Frontier, (Word32)(0x4ull));
	P_1 = (Objptr)Q_16;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	O(Word32, P_1, 0) = (Word32)(Word32)(0x0ull);
	O(Objptr, P_1, 4) = G(Objptr, 15);
	O(Objptr, P_1, 8) = P_0;
	S(CPointer, 0) = 10;
	S(Objptr, 32) = P_1;
	S(CPointer, 28) = 12;
	Push (32);
	goto concat_0;
L_73:
	S(CPointer, 28) = 15;
	Push (32);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
L_74:
	Push (-32);
	goto L_68;
default:
switch ((Word32)P_0) {
case (Word32)(0x1ull):
	W32_0 = CPointer_lt (O(CPointer, GCState, 4), Frontier);
	BNZ (W32_0, L_65);
L_64:
	goto L_47;
L_65:
	S(CPointer, 28) = 14;
	Push (32);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
L_66:
	Push (-32);
	goto L_64;
default:
	P_1 = O(Objptr, P_0, 8);
	W8_0 = O(Word8, P_0, 0);
	P_0 = P_1;
	goto L_42;
}
}
case (Word8)(0x2ull):
switch ((Word32)P_0) {
case (Word32)(0x1ull):
	W32_0 = CPointer_lt (O(CPointer, GCState, 4), Frontier);
	BNZ (W32_0, L_79);
L_78:
	goto L_47;
L_79:
	S(CPointer, 28) = 16;
	Push (32);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
L_80:
	Push (-32);
	goto L_78;
default:
	P_1 = O(Objptr, P_0, 8);
	W8_0 = O(Word8, P_0, 0);
	P_0 = P_1;
	goto L_42;
}
default:
switch ((Word32)P_0) {
case (Word32)(0x1ull):
	W32_0 = CPointer_lt (O(CPointer, GCState, 4), Frontier);
	BNZ (W32_0, L_57);
L_46:
	goto L_47;
L_57:
	S(CPointer, 28) = 13;
	Push (32);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
L_58:
	Push (-32);
	goto L_46;
default:
	P_1 = O(Objptr, P_0, 8);
	W8_0 = O(Word8, P_0, 0);
	P_0 = P_1;
	goto L_42;
}
}
}
case 16:
	goto L_80;
case 15:
	goto L_74;
case 17:
L_72:
	Push (-32);
L_70:
	P_0 = S(Objptr, 8);
	goto L_49;
case 12:
	Push (-32);
	S(Objptr, 8) = S(Objptr, 32);
	W32_0 = CPointer_lt (O(CPointer, GCState, 4), Frontier);
	BNZ (W32_0, L_71);
	goto L_70;
L_71:
	S(CPointer, 28) = 17;
	Push (32);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
	goto L_72;
case 14:
	goto L_66;
case 13:
	goto L_58;
case 10:
	Push (-4);
L_53:
	Stdio_print (G(Objptr, 14));
	FlushFrontier();
	FlushStackTop();
	MLton_halt (GCState, (Word32)(0x1ull));
	CacheFrontier();
	CacheStackTop();
case 11:
	Push (-32);
	S(Objptr, 8) = S(Objptr, 32);
	Stdio_print (S(Objptr, 8));
	P_0 = O(Objptr, S(Objptr, 20), 8);
	W32_0 = O(Word32, P_0, 0);
	BNZ (W32_0, L_52);
	O(Word32, P_0, 0) = (Word32)(0x1ull);
	FlushFrontier();
	FlushStackTop();
	MLton_halt (GCState, (Word32)(0x1ull));
	CacheFrontier();
	CacheStackTop();
L_52:
	goto L_53;
case 9:
	Push (-4);
	S(Objptr, 12) = GPNR(0);
	W32_0 = CPointer_lt (O(CPointer, GCState, 4), Frontier);
	BNZ (W32_0, L_82);
	goto L_40;
L_82:
	S(CPointer, 28) = 18;
	Push (32);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
	goto L_83;
case 8:
	Push (-32);
	S(Word32, 16) = S(Word32, 32);
	W32_0 = O(Word32, S(Objptr, 12), 0);
	BNZ (W32_0, L_37);
	O(Word32, S(Objptr, 12), 0) = (Word32)(0x1ull);
	FlushFrontier();
	FlushStackTop();
	MLton_halt (GCState, (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
L_37:
	Stdio_print (G(Objptr, 12));
	FlushFrontier();
	FlushStackTop();
	MLton_halt (GCState, (Word32)(0x1ull));
	CacheFrontier();
	CacheStackTop();
case 7:
	goto L_30;
case 32:
main_0:
	S(Word32, 4) = O(Word32, GCState, 16);
	W32_0 = CPointer_lt (O(CPointer, GCState, 12), StackTop);
	BNZ (W32_0, L_109);
	goto L_10;
L_109:
	S(CPointer, 12) = 22;
	Push (16);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
	goto L_110;
case 3:
L_8:
	Push (-8);
L_2:
	C(Word32, Frontier) = (Word32)(0x23ull);
	Q_0 = CPointer_add (Frontier, (Word32)(0x4ull));
	G(Objptr, 0) = (Objptr)Q_0;
	Frontier = CPointer_add (Frontier, (Word32)(0x8ull));
	O(Objptr, G(Objptr, 0), 0) = (Objptr)(Word32)(0x1ull);
	S(CPointer, 4) = 0;
	Push (8);
	FlushFrontier();
	FlushStackTop();
	CReturnP = GC_arrayAllocate (GCState, (Word32)(0x30ull), (Word32)(0x0ull), (Word32)(0x11ull));
	CacheFrontier();
	CacheStackTop();
L_3:
	Push (-8);
	G(Objptr, 1) = CReturnP;
	S(CPointer, 4) = 1;
	Push (8);
	FlushFrontier();
	FlushStackTop();
	CReturnP = GC_arrayAllocate (GCState, (Word32)(0x30ull), (Word32)(0x0ull), (Word32)(0x11ull));
	CacheFrontier();
	CacheStackTop();
L_4:
	Push (-8);
	G(Objptr, 2) = CReturnP;
	S(CPointer, 4) = 2;
	Push (8);
	FlushFrontier();
	FlushStackTop();
	CReturnP = GC_arrayAllocate (GCState, (Word32)(0x30ull), (Word32)(0x0ull), (Word32)(0x11ull));
	CacheFrontier();
	CacheStackTop();
L_5:
	Push (-8);
	G(Objptr, 3) = CReturnP;
	C(Word32, Frontier) = (Word32)(0x1Dull);
	Q_3 = CPointer_add (Frontier, (Word32)(0x4ull));
	G(Objptr, 4) = (Objptr)Q_3;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	G(Word32, 2) = WordU16_extdToWord32 ((Word16)(Word16)(0x4641ull));
	G(Word32, 3) = Word32_lshift (G(Word32, 2), (Word32)(0x10ull));
	O(Word32, G(Objptr, 4), 0) = (Word32)G(Word32, 3);
	O(Word32, G(Objptr, 4), 4) = (Word32)(Word32)(0x0ull);
	O(Objptr, G(Objptr, 4), 8) = (Objptr)(Word32)(0x1ull);
	C(Word32, Frontier) = (Word32)(0x1Dull);
	Q_2 = CPointer_add (Frontier, (Word32)(0x4ull));
	G(Objptr, 5) = (Objptr)Q_2;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	G(Word32, 4) = WordU16_extdToWord32 ((Word16)(Word16)(0x6661ull));
	G(Word32, 5) = Word32_lshift (G(Word32, 4), (Word32)(0x10ull));
	O(Word32, G(Objptr, 5), 0) = (Word32)G(Word32, 5);
	O(Word32, G(Objptr, 5), 4) = (Word32)(Word32)(0x0ull);
	O(Objptr, G(Objptr, 5), 8) = G(Objptr, 4);
	C(Word32, Frontier) = (Word32)(0x1Full);
	Q_1 = CPointer_add (Frontier, (Word32)(0x4ull));
	G(Objptr, 6) = (Objptr)Q_1;
	Frontier = CPointer_add (Frontier, (Word32)(0x10ull));
	O(Word32, G(Objptr, 6), 0) = (Word32)(Word32)(0x0ull);
	O(Objptr, G(Objptr, 6), 4) = G(Objptr, 7);
	O(Objptr, G(Objptr, 6), 8) = (Objptr)(Word32)(0x1ull);
	S(CPointer, 4) = 6;
	Push (8);
	goto main_0;
case 6:
	Push (-8);
	MLton_bug (G(Objptr, 8));
case 2:
	goto L_5;
case 1:
	goto L_4;
case 0:
	goto L_3;
case 33:
	G(Word32, 0) = CPointer_lt (O(CPointer, GCState, 12), StackTop);
	BNZ (G(Word32, 0), L_7);
	G(Word32, 1) = CPointer_lt (O(CPointer, GCState, 4), Frontier);
	BNZ (G(Word32, 1), L_7);
	goto L_2;
L_7:
	S(CPointer, 4) = 3;
	Push (8);
	FlushFrontier();
	FlushStackTop();
	GC_collect (GCState, (Word32)(0x0ull), (Word32)(0x0ull));
	CacheFrontier();
	CacheStackTop();
	goto L_8;
EndChunk
